export const categoriesData = [
  {
    id: 1,
    title: "Baby Product",
    imageUrl: "https://i.picsum.photos/id/0/200/200.jpg",
    route: "shop/babyProduct",
  },
  {
    id: 2,
    title: "Chocolate & Candy",
    imageUrl: "https://i.picsum.photos/id/10/200/200.jpg",
    route: "shop/chocolateCandy",
  },
  {
    id: 3,
    title: "Electronics",
    imageUrl: "https://i.picsum.photos/id/20/200/200.jpg",
    route: "shop/electronics",
  },
  {
    id: 4,
    title: "Family Planning",
    imageUrl: "https://i.picsum.photos/id/30/200/200.jpg",
    route: "shop/familyPlanning",
  },
  {
    id: 5,
    title: "Groceries",
    imageUrl: "https://i.picsum.photos/id/40/200/200.jpg",
    route: "shop/groceries",
  },
  {
    id: 6,
    title: "Health & Hygiene",
    imageUrl: "https://i.picsum.photos/id/50/200/200.jpg",
    route: "shop/healthHygiene",
  },
  {
    id: 7,
    title: "Medicine",
    imageUrl: "https://i.picsum.photos/id/60/200/200.jpg",
    route: "shop/medicine",
  },
  {
    id: 8,
    title: "Lockdown Essentials",
    imageUrl: "https://i.picsum.photos/id/70/200/200.jpg",
    route: "shop/lockdownEssentials",
  },
  {
    id: 9,
    title: "Pet Products",
    imageUrl: "https://i.picsum.photos/id/80/200/200.jpg",
    route: "shop/petProducts",
  },
  {
    id: 10,
    title: "Office Supplies",
    imageUrl: "https://i.picsum.photos/id/90/200/200.jpg",
    route: "shop/officeSupplies",
  },
  {
    id: 11,
    title: "Snacks",
    imageUrl: "https://i.picsum.photos/id/31/200/200.jpg",
    route: "shop/snacks",
  },
  {
    id: 12,
    title: "Toiletries",
    imageUrl: "https://i.picsum.photos/id/33/200/200.jpg",
    route: "shop/toiletries",
  },
  {
    id: 13,
    title: "Smoking Essentials",
    imageUrl: "https://i.picsum.photos/id/34/200/200.jpg",
    route: "shop/smokingEssentials",
  },
];
