export const categoriesData = [
  {
    id: 1,
    title: "Baby Product",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/babyProduct",
  },
  {
    id: 2,
    title: "Chocolate & Candy",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/chocolateCandy",
  },
  {
    id: 3,
    title: "Electronics",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/electronics",
  },
  {
    id: 4,
    title: "Family Planning",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/familyPlanning",
  },
  {
    id: 5,
    title: "Groceries",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/groceries",
  },
  {
    id: 6,
    title: "Health & Hygiene",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/healthHygiene",
  },
  {
    id: 7,
    title: "Medicine",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/medicine",
  },
  {
    id: 8,
    title: "Lockdown Essentials",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/lockdownEssentials",
  },
  {
    id: 9,
    title: "Pet Products",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/petProducts",
  },
  {
    id: 10,
    title: "Office Supplies",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/officeSupplies",
  },
  {
    id: 11,
    title: "Snacks",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/snacks",
  },
  {
    id: 12,
    title: "Toiletries",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/toiletries",
  },
  {
    id: 13,
    title: "Smoking Essentials",
    imageUrl: "https://via.placeholder.com/200",
    route: "shop/smokingEssentials",
  },
];
